### ISSUE TITLE
Monero v7 PoW

### ISSUE THREAD

**Issue by agrus** [enwillyado/xmrig-proxy#5]
Does project updated to support Monero v7 PoW? analog of v2.5 of original xmrig

**Comment by enwillyado** [comment]
Yes, of course.

**Comment by agrus** [comment]
did not see any variant options in code

**Comment by enwillyado** [comment]
The **proxy** version never miner nor check shares. It is compatabile with STRATUM protocol only, it does not need know about PoW.

**Comment by agrus** [comment]
Ok, and what about miner?

**Comment by enwillyado** [comment]
Miner is here: https://github.com/enwillyado/xmrig
And it is **fully compatible** with the PoW v7 since 3.3.3-3 release: https://github.com/enwillyado/xmrig/releases
